monsieurbiz_sylius_settings:
    plugins:
        monsieurbiz_contact_request.contact:
            vendor_name: Monsieur Biz
            plugin_name: monsieurbiz.contact_request.settings.plugin_name
            description: monsieurbiz.contact_request.settings.description
            icon: envelope outline
            use_locales: true
            classes:
                form: MonsieurBiz\SyliusContactRequestPlugin\Form\Type\ContactSettingsType
            default_values:
                field_name_displayed: true
                field_name_required: true
                field_company_displayed: true
                field_company_required: false
                field_phone_number_displayed: true
                field_phone_number_required: false
